# Generated by Django 3.1 on 2020-08-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('b_no', models.AutoField(db_column='b_no', primary_key=True, serialize=False)),
                ('b_title', models.CharField(db_column='b_title', max_length=255)),
                ('b_note', models.CharField(db_column='b_note', max_length=4096)),
                ('b_writer', models.CharField(db_column='b_writer', max_length=50)),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
    ]
